name: Clang Format Check

on: 
    pull_request:
        types: [opened, edited, reopened, synchronize]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        continue-on-error: true
        run: |
          # Check formatting
          clang-format --dry-run --Werror $(find . -regex '.*\.\(tpp\|cpp\|hpp\|cc\|c\|h\)')
